export THEOS_PACKAGE_SCHEME=rootless
export THEOS_DEVICE_IP = 192.168.86.45

PACKAGE_VERSION=$(THEOS_PACKAGE_BASE_VERSION)

include $(THEOS)/makefiles/common.mk

SUBPROJECTS += Tweak

include $(THEOS_MAKE_PATH)/aggregate.mk